#!/bin/bash                        
#$ -o /u/home/r/rwolff/diversity_ecology/scripts/shell_scripts/bzip_out
#$ -e /u/home/r/rwolff/diversity_ecology/scripts/shell_scripts/bzip_err
#$ -cwd                           
#$ -r y                           
#$ -j y                        
#$ -l h_data=3G                 
#$ -l h_rt=8:00:00               
#$ -t 1-151                        

#readarray files < /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/species_snps.txt
readarray files < /u/project/ngarud/Garud_lab/metagenomic_fastq_files/Korpela/data/genes/species_genes.txt

files=(null ${files[@]}) # this pads the file with an extra line in the beginning. 
species=${files[$SGE_TASK_ID]}
indir=/u/project/ngarud/Garud_lab/metagenomic_fastq_files/Korpela/data
echo $species

bzip2 ${indir}/species/coverage.txt
bzip2 ${indir}/species/count_reads.txt
bzip2 ${indir}/species/relative_abundance.txt
bzip2 ${indir}/species/species_prevalence.txt
